### ISSUE TITLE
Go OpenTracing Error Logging

### ISSUE THREAD

**Issue by rnburn** [grpc-ecosystem/grpc-opentracing#22]
Go's OpenTracing error logging uses different [naming](https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/client.go#L75) than that recommended by the  OpenTracing [semantic conventions](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#captured-errors). Any reason for the discrepancy? or why it can't be reconciled?

**Comment by bhs** [comment]
@rnburn the naming predates the standard – this is basically just a bug, certainly no good reason for it to stay as-is.

**Comment by rnburn** [comment]
Ok. Thanks. I'll put in a PR to update it.
