### ISSUE TITLE
Can we get semver releases?

### ISSUE THREAD

**Issue by bufdev** [grpc-ecosystem/grpc-opentracing#30]
Re https://github.com/grpc-ecosystem/grpc-opentracing/issues/28

**Comment by bhs** [comment]
@peter-edge sorry for the delay, I'm doing a pass through open issues.

Semver releases SGTM in principle. You just want a git tag??

**Comment by tedsuo** [comment]
Hi @peter-edge, the OpenTracing community is taking this repo over, and we'll be splitting it out into separate language components, which will allow us to do semver in a more meaningful manner.

**Comment by tedsuo** [comment]
Closing this issue as repos have now been moved and are properly versioned.
