### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by bufdev** [grpc-ecosystem/grpc-opentracing#31]
Preferably MIT, there is no license right now on this.

**Comment by bhs** [comment]
@peter-edge how about ASF2?

Agree that we should have a LICENSE one way or the other.

**Comment by pquerna** [comment]
there is a license in the root of the repository: https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/LICENSE

?

**Comment by bufdev** [comment]
Weird, didn't see it before - sounds good!
