### ISSUE TITLE
Update the grpc and opentracing version

### ISSUE THREAD

**Issue by zhuchenwang** [grpc-ecosystem/grpc-opentracing#33]
The gRPC version is 1.4.0 and opentracing-api is 0.30.0.

Looks like the library doesn't work with the latest version.

**Comment by devoxel** [comment]
Is this being worked on? Seems like a fairly high priority issue

**Comment by matthewrj** [comment]
+1

**Comment by hzariv** [comment]
This PR is pending https://github.com/grpc-ecosystem/grpc-opentracing/pull/36 
@matthewrj had anyone been assigned or review this?

**Comment by hzariv** [comment]
Pings @bhs and @kcamenzind

**Comment by bhs** [comment]
(Can this be closed now, @hzariv?)

**Comment by hzariv** [comment]
@bhs It can be if we have released version 0.3.0 of grpc-opentracing to maven central.

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.opentracing.contrib%22%20AND%20a%3A%22grpc-opentracing%22

Right now only version 0.2.0 is there.

**Comment by hzariv** [comment]
@bhs could you please help with releasing this artifact to maven central?

**Comment by artworx** [comment]
Any update on this? I'm considering using this library and I would really appreciate the new version.

**Comment by tedsuo** [comment]
Hi All! We are going to move this work from gRPC to the OpenTracing community organization, and split it into language specific issues. As part of that, we will update java to the latest API. But I'll see about getting the last version of this pushed to maven before the move.

**Comment by alexnederlof** [comment]
Any progress here?

**Comment by tewner** [comment]
Pushing v0.3.0 to Maven Central would also help me.

**Comment by bhs** [comment]
Per https://oss.sonatype.org/#nexus-search;quick~grpc-opentracing, I pushed v0.3.0.
```
<dependency>
  <groupId>io.opentracing.contrib</groupId>
  <artifactId>grpc-opentracing</artifactId>
  <version>0.3.0</version>
</dependency>
```

Millions of apologies for how long this took. (@tedsuo, I agree that this repo should still move to `opentracing-contrib` and the languages should be decoupled)

**Comment by rflueras** [comment]
Hello,

I think there are still some issues with the library when it comes to the new:

```
<dependency>
    <groupId>io.opentracing</groupId>
    <artifactId>opentracing-api</artifactId>
    <version>0.31.0</version>
</dependency>
```

There are major modifications which cause issues such as:
1) Missing BaseSpan: https://github.com/jaegertracing/jaeger-client-java/pull/313, https://github.com/opentracing/opentracing-java/issues/237
2) Backward compatiblity: https://github.com/opentracing/opentracing-java/issues/189
Along with other problems...

Version updates: https://medium.com/opentracing/announcing-java-v0-31-release-candidate-6e1f1a922d2e

The idea is that they made some "updates" / minor hacks for the many people which use the 0.30.0 version and want to upgrade (to 0.31.0) in a none regressive way, but in our case for the Client/Server Tracing Interceptors I consider it way too complicated to be left unresolved for further development.

Fix for regular development: https://github.com/opentracing/opentracing-java-v030

The opentracing-spring-web-autoconfigure (0.3.2) only works with opentracing-api (0.31.0), and whatever other flow I would adapt, it still requires the latest version to work properly, but I get issues regarding Span.log / Span.setTag from BaseSpan no longer found.

Maybe there is some quick-fix I could use.

If you have time look into this, that would be great.

Thank you!

**Comment by tedsuo** [comment]
Hi @rflueras this library has been moved here: https://github.com/opentracing-contrib/java-grpc

That version works with `0.31.0`. I'll be updating this repo to make it more clear that development has moved. Please open an issue there if that version is not solving your issue.

Thanks,
Ted

**Comment by rflueras** [comment]
Thank you so much!

Works now :).

**Comment by srujann** [comment]
@tedsuo can you please update the ReadMe that project has moved to https://github.com/opentracing-contrib/java-grpc as this one still has issues 0.31.0 version of opentracing.
