### ISSUE TITLE
Errors not always being reported

### ISSUE THREAD

**Issue by iheanyi** [grpc-ecosystem/grpc-opentracing#34]
Recently, a change was merged in that mad assumptions about the types of errors and 
whether or not they should be reported. I think that regardless of type, the error should be reported so long as it `!= nil`. Additionally, you can't always assume that the errors will be of the type `grpc.Error`, because some errors in the Server may not always be a gRPC error. For example, errors returned from `database/sql` that get propagated back to a gRPC endpoint will be marked as `0xx` unknown. This bug has messed up error reporting in our applications at work, so I'm sure others have ran into the same problem.

For reference: 

Relevant Lines: https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/errors.go#L53-L69
The PR: https://github.com/grpc-ecosystem/grpc-opentracing/pull/27

**Comment by tedsuo** [comment]
Closing this issue as it has been resolved. Thanks!

**Comment by iheanyi** [comment]
@tedsuo Thank you! Could you point me to the commit that resolves this? I'm coming up short. Thanks in advance.
